# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  branches:
      include:
         - Jacky-Feature
  paths:
      include:
         - asd-project/client/*

variables:
  - name: projectPath
    value: './asd-project/client/'
  - name: serverPath
    value: './asd-project/server/'

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install
  workingDirectory: ${{variables.projectPath}}
  displayName: 'npm install client'

- script: |
    npm install
  workingDirectory: ${{variables.serverPath}}
  displayName: 'npm install server'

- script: |
    npm run dev
  workingDirectory:  ${{variables.serverPath}}
  displayName: 'npm run dev server'

- script: |
    npm start
  workingDirectory:  ${{variables.projectPath}}
  displayName: 'npm start client'

- script: |
    ./node_modules/.bin/cypress run --browser chrome
  workingDirectory: ${{variables.projectPath}}
  displayName: 'Run cypress tests'

- task: PublishTestResults@2
  displayName: 'Publish test results'
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: '*.xml'
    searchFolder: 
      '$(System.DefaultWorkingDirectory)/cypress/reports/junit'
    mergeTestResults: true
    testRunTitle: 'Cypress tests'

