# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  branches:
      include:
         - main

variables:
  - name: projectPath
    value: './asd-project/client/'
  - name: serverPath
    value: './asd-project/server/'

pool:
  vmImage: ubuntu-latest

stages:
- stage: 'Prerequisite'
  displayName: 'Prerequisite'
  jobs: 
  - job: 'Build'
    displayName: 'Build job'
  
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '10.x'
      displayName: 'Install Node.js'

    - script: |
        npm install
      workingDirectory: ${{variables.projectPath}}
      displayName: 'npm install client'

    - script: |
        npm install
      workingDirectory: ${{variables.serverPath}}
      displayName: 'npm install server'

- stage: 'Publish_Test'
  displayName: 'Publish Test'
  jobs: 
  - job: 'Publish'
    displayName: 'Publish Test'
  
    steps:
    - task: PublishTestResults@2
      displayName: 'Publish test results'
      inputs:
        testResultsFormat: 'JUnit'
        testResultsFiles: '*.xml'
        searchFolder: 
          '${{variables.projectPath}}/cypress/reports/junit'
        mergeTestResults: true
        testRunTitle: 'Cypress tests'


 




